name: LH

env:
  REQUEST_TIMEOUT: 30000

on:
  # schedule:
  # - cron: '30 4 * * 1-5'

  #   push:
  #     branches:
  #       - main

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm i lighthouse
          npm i lighthouse chrome-launcher
          npm i node-fetch
          npm install --save dotenv
          npm i nodemailer

      - name: Run JS with args
        run: |
          mkdir -p reports
          node lighthouse.mjs

      - name: Upload Lighthouse Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: reports/lighthouse-report.html

      - name: Run JS with args
        run: |
          node Run_StartMail.js
